import os
from botsmith.agents.base_agent import BaseAgent


class ProjectScaffoldAgent(BaseAgent):
    """
    Deterministic agent that creates a clean, scalable bot project structure.
    No LLM calls. Pure filesystem operations.
    """

    def _execute(self, task: str, context):
        fs = context.get("filesystem")
        project_name = context.get("project_name")

        if fs is None or not project_name:
            raise ValueError("filesystem and project_name are required")

        # Root directory
        fs.mkdir(project_name)

        # src/ directory
        src_path = os.path.join(project_name, "src")
        fs.mkdir(src_path)

        # package directory: src/<project_name>/
        package_path = os.path.join(src_path, project_name)
        fs.mkdir(package_path)

        # __init__.py (required for importable package)
        fs.write_file(os.path.join(package_path, "__init__.py"), "")

        # main.py (inside package)
        fs.write_file(
            os.path.join(package_path, "main.py"),
            f'''"""
Entry point of the {project_name} bot.
Generated by BotSmith - https://github.com/blexyyyyy/botsmith
"""

def main():
    print("Bot '{project_name}' is running!")
    # TODO: Add your bot logic here

if __name__ == "__main__":
    main()
'''
        )

        # run.py (at project root for easy execution)
        fs.write_file(
            os.path.join(project_name, "run.py"),
            f'''#!/usr/bin/env python3
"""
Quick-start script for {project_name}.
Usage: python run.py
"""
import sys
import os

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

from {project_name}.main import main

if __name__ == "__main__":
    print("=" * 50)
    print(f"  Starting {project_name}")
    print("  Generated by BotSmith")
    print("=" * 50)
    main()
'''
        )

        # requirements.txt (common dependencies)
        fs.write_file(
            os.path.join(project_name, "requirements.txt"),
            f"""# Dependencies for {project_name}
# Generated by BotSmith

requests>=2.28.0
python-dotenv>=1.0.0
"""
        )

        # README.md (comprehensive)
        fs.write_file(
            os.path.join(project_name, "README.md"),
            f'''# {project_name}

> 🤖 Generated by [BotSmith](https://github.com/blexyyyyy/botsmith) - AI-Powered Bot Generator

## What is BotSmith?

BotSmith is a governed multi-agent system that converts natural language requests into planned, validated, and executable Python bots. It focuses on control, correctness, and extensibility.

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run the bot
python run.py
```

## Project Structure

```
{project_name}/
├── run.py              # Quick-start script
├── requirements.txt    # Python dependencies
├── src/
│   └── {project_name}/
│       ├── __init__.py
│       └── main.py     # Bot entry point
└── tests/
    └── test_basic.py
```

## Development

```bash
# Install in development mode
pip install -e .

# Run tests
pytest tests/
```

## License

MIT License - Generated by BotSmith
'''
        )

        # .gitignore
        fs.write_file(
            os.path.join(project_name, ".gitignore"),
            "__pycache__/\\n*.pyc\\n.env\\nbuild/\\ndist/\\n*.egg-info/\\n.venv/\\nvenv/\\n"
        )

        # LICENSE
        fs.write_file(
            os.path.join(project_name, "LICENSE"),
            "MIT License\\n\\nCopyright (c) 2024 BotSmith Generated Project\\n..."
        )
        
        # tests/ directory
        tests_path = os.path.join(project_name, "tests")
        fs.mkdir(tests_path)
        fs.write_file(os.path.join(tests_path, "__init__.py"), "")
        fs.write_file(
            os.path.join(tests_path, "test_basic.py"),
            f"def test_import():\\n    import {project_name}\\n    assert True\\n"
        )

        # pyproject.toml
        fs.write_file(
            os.path.join(project_name, "pyproject.toml"),
            f'''[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "A bot created with BotSmith - AI-Powered Bot Generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.28.0",
    "python-dotenv>=1.0.0",
]

[project.scripts]
{project_name} = "{project_name}.main:main"
'''
        )

        return {
            "project_path": project_name,
            "package_path": package_path,
            "files": [
                os.path.join(project_name, "run.py"),
                os.path.join(package_path, "main.py"),
                os.path.join(package_path, "__init__.py"),
                os.path.join(project_name, "requirements.txt"),
                os.path.join(project_name, "README.md"),
                os.path.join(project_name, "pyproject.toml"),
                os.path.join(project_name, ".gitignore"),
                os.path.join(tests_path, "test_basic.py")
            ],
            "scaffolded": True,
        }
