import os
from botsmith.core.base.agent import BaseAgent


class ProjectScaffoldAgent(BaseAgent):
    """
    Deterministic agent that creates a clean, scalable bot project structure.
    No LLM calls. Pure filesystem operations.
    """

    def _execute(self, task: str, context):
        fs = context.get("filesystem")
        project_name = context.get("project_name")

        if fs is None or not project_name:
            raise ValueError("filesystem and project_name are required")

        # Root directory
        fs.mkdir(project_name)

        # src/ directory
        src_path = os.path.join(project_name, "src")
        fs.mkdir(src_path)

        # package directory: src/<project_name>/
        package_path = os.path.join(src_path, project_name)
        fs.mkdir(package_path)

        # __init__.py (required for importable package)
        fs.write_file(os.path.join(package_path, "__init__.py"), "")

        # main.py
        fs.write_file(
            os.path.join(package_path, "main.py"),
            f'''"""
Entry point of the {project_name} bot.
"""

def main():
    print("Bot '{project_name}' is running!")

if __name__ == "__main__":
    main()
'''
        )

        # requirements.txt
        fs.write_file(
            os.path.join(project_name, "requirements.txt"),
            "requests\n"
        )

        # README.md
        fs.write_file(
            os.path.join(project_name, "README.md"),
            f"# {project_name}\n\nGenerated by BotSmith.\n"
        )

        # .gitignore
        fs.write_file(
            os.path.join(project_name, ".gitignore"),
            "__pycache__/\n*.pyc\n.env\nbuild/\ndist/\n*.egg-info/\n"
        )

        # LICENSE
        fs.write_file(
            os.path.join(project_name, "LICENSE"),
            "MIT License\n\nCopyright (c) 2024 BotSmith Generated Project\n..."
        )
        
        # tests/ directory
        tests_path = os.path.join(project_name, "tests")
        fs.mkdir(tests_path)
        fs.write_file(os.path.join(tests_path, "__init__.py"), "")
        fs.write_file(
            os.path.join(tests_path, "test_basic.py"),
            f"def test_import():\n    import {project_name}\n    assert True\n"
        )

        # pyproject.toml
        fs.write_file(
            os.path.join(project_name, "pyproject.toml"),
            f'''[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{project_name}"
version = "0.1.0"
description = "A bot created with BotSmith"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
]

[project.scripts]
{project_name} = "{project_name}.main:main"
'''
        )

        return {
            "project_path": project_name,
            "package_path": package_path,
            "files": [
                os.path.join(package_path, "main.py"),
                os.path.join(package_path, "__init__.py"),
                os.path.join(project_name, "requirements.txt"),
                os.path.join(project_name, "README.md"),
                os.path.join(project_name, "pyproject.toml"),
                os.path.join(project_name, ".gitignore"),
                os.path.join(tests_path, "test_basic.py")
            ],
            "scaffolded": True,
        }
