"""
Entry point of the weather_bot bot.
Generated by BotSmith - https://github.com/blexyyyyy/botsmith
"""

def main():
    print("Bot 'weather_bot' is running!")
    # TODO: Add your bot logic here

if __name__ == "__main__":
    main()
