#!/usr/bin/env python3
"""
Quick-start script for debug_bot_scaffold.
Usage: python run.py
"""
import sys
import os

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

from debug_bot_scaffold.main import main

if __name__ == "__main__":
    print("=" * 50)
    print(f"  Starting debug_bot_scaffold")
    print("  Generated by BotSmith")
    print("=" * 50)
    main()
